name: ny_taxi
version: 1.0.0
config-version: 2

profile: ny_taxi

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ny_taxi:
    +materialized: view
