services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=ny_taxi
    volumes:
      - "D:/Development/Data-Engineering/Datasets/ny_taxi_pg_data:/var/lib/postgresql/data:rw"
    ports:
      - "6543:5432"
    networks:
      - airflow
  pgadmin:
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

networks:
  airflow:
    # external: true
    name: airflow_default

