
version: 2



sources:
  - name: taxi_data
    database: raw_data
    schema: nyc_taxi
    tables:
      - name: green_taxi_trips
      - name: yellow_taxi_trips

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
